---
title: "Edfinity"
author: "Nicole Higgins"
date: "1/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pracma)
```

```{r}
v1 = c(1,-1,1,-1)
v2 = c(1,1,-1,-1)
v3 = c(1,-1,-1,1)
w = c(1,2,3,4)

a = t(w)%*%v1/t(v1)%*%v1
b = t(w)%*%v2/t(v2)%*%v2
t(w)%*%v3/t(v3)%*%v3

w2 = a*v1+b*v2
w-w2
v1%*%w2
v2%*%w2
v3%*%w2
```
thus A is orthogonal and B is not.

```{r}
w = c(-3,1,-13)
w%*%A[,1]/A[,1]%*%A[,1]
w%*%A[,2]/A[,2]%*%A[,2]
w%*%A[,3]/A[,3]%*%A[,3]
```
thus w = -5 A[,1] + 4 A[,2] + 2 A[,3]




```{r}
x0 = c(1,0)
A = cbind(c(1/2,1/2),
          c(1/10,9/10))

for (i in 1:2000) {
  x0 = A %*% x0
}
x0
eigen(A)
```
```{r}

```



```{r}
A = cbind(c(5,4,3,1,2),c(4,4,3,1,2),c(1,1,1,1,1),diag(5))

B = cbind(c(5,4,3,1,2),c(4,4,3,1,2),c(1,1,1,1,1),
          c(0,1,0,0,0),c(0,0,1,0,0))

rref(A)
rref(B)
```

```{r}
cyan = c(0,1,1)
magenta = c(.8, .25, .5)
yellow = c(1.0, .9, .1)
tan = c(1.0, 0.665, 0.31)
olive = c(.7,.7,.4)
dodger = c(.12,.56,1.0)

B = cbind(magenta, yellow, tan, dodger)

B
round(rref(B), 4)
```
## Quiz 3

```{r}
A = cbind(c(1,2,3,4),
          c(1,1,1,1))
t(A)%*%c(6,10,12,11)
B = cbind(c(30,10),
          c(10,4),
          c(106,39))
rref(B)
```
thus scalars are 7 and -1, respectively:
A^n x0 = λ1^n 7 v1 - λ2^n v2
thus closed formula:
xvn = 7(2)^n + 2(-1)^n
yvn = 7(2)^n -(-1)^n

# Quiz 4

```{r}
x = c(1,2,3,4,5,6,7,8,9)
y = c(5,3,1,3,3,8,7,9,10)
(A = cbind(x^0,x,x^2))
xhat = solve(t(A)%*%A,t(A)%*%y)
xhat
yhat = A %*% xhat
r = y - yhat
sqrt(t(r) %*% r)
```

```{r}
S = cbind(c(1,-1,1,1),
          c(1,1,-1,1))
s = rbind(c(1,-1,1,1),
          c(1,1,-1,1))
Sp = cbind(c(0,1,1,0),
           c(-1,0,0,1))
s1 = c(1,-1,1,1)
s2 = c(1,1,-1,1)
v = c(3,0,2,7)
l = ((v%*%s1)/(s1%*%s1))%*%s1+((v%*%s2)/(s2%*%s2))%*%s2
r = v - l
sqrt(r %*% t(r))
v - 2*r
```

```{r}
P = cbind(c(0.7,0.3),
          c(0.5,0.5))
eigen(P)
eigen(P)$vectors%*%cbind(c(1,0),c(0,0))%*%solve(eigen(P)$vectors)
eigen(P)$vectors[2,1]/eigen(P)$vectors[1,1]
```

```{r}
P = 1/10*cbind(c(6,4,2,0,-2),c(4,3,2,1,0),c(2,2,2,2,2),c(0,1,2,3,4),c(-2,0,2,4,6))
v = c(30,30,10,40,50)
Pr = 1/10*rbind(c(6,4,2,0,-2),c(4,3,2,1,0),c(2,2,2,2,2),c(0,1,2,3,4),c(-2,0,2,4,6))
rref(Pr) # thus Pperp is the null space:
Pp = cbind(c(1,-2,1,0,0),
           c(2,-3,0,1,0),
           c(3,-4,0,0,1))
aug = cbind(P,Pp,v) 
rref(aug) # finding scalars of P and Pp vectors that give us v
# applying scalars to appropriate vectors to find w and z
(w = cbind(-210/10*c(6,4,2,0,-2) + 370/10*c(4,3,2,1,0))) 
(z = cbind(-22*c(1,-2,1,0,0) + 3*c(2,-3,0,1,0) + 8*c(3,-4,0,0,1)))
rref(P)
```

















